Repository cloudera/cybersec, pull requests merged in 2023-05, with the labels that each got.

#4 [CYB-117] Changed the parser field addition/removal logic
  flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-page/components/custom-form/components/multi-input/multi-input.component.html
  flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-page/components/custom-form/custom-form.component.ts
  flink-cyber/metron-parser-chain/parser-chains-config-service/src/main/java/com/cloudera/parserchains/queryservice/model/describe/ConfigParamDescriptor.java
  flink-cyber/metron-parser-chain/parser-chains-config-service/src/main/java/com/cloudera/parserchains/queryservice/service/DefaultParserDiscoveryService.java
  flink-cyber/metron-parser-chain/parser-chains-config-service/src/test/java/com/cloudera/parserchains/queryservice/model/describe/ParserDescriptorTest.java
  flink-cyber/metron-parser-chain/parser-chains-config-service/src/test/java/com/cloudera/parserchains/queryservice/service/DefaultParserDiscoveryServiceTest.java
  flink-cyber/metron-parser-chain/parser-chains-core/src/main/java/com/cloudera/parserchains/core/catalog/Configurable.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/CsvTextParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/DelimitedTextParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/GrokParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/JSONParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/JSONPathParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/RemoveFieldParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/RenameFieldParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/TimestampFormatParser.java
  flink-cyber/metron-parser-chain/parser-chains-parsers/src/main/java/com/cloudera/parserchains/parsers/XPathParser.java
Labels: checked on a cluster, ready to review

#7 [CYB-126] Updated antlr to 4.9.3
  flink-cyber/flink-parse/flink-parse-metron/pom.xml
  flink-cyber/metron-parser-chain/parser-chains-parsers/pom.xml
  flink-cyber/pom.xml
Labels: checked on a cluster, ready to review, ready to merge

#21 [CYB-148] Proper Enter handling for adding values to multi-fields
  flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-page/components/custom-form/components/multi-input/multi-input.component.html
  flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-page/components/custom-form/components/multi-input/multi-input.component.ts
Labels: checked on a cluster, ready to review

#12 [CYB-132] Cloudera Manager does not generate kafka broker url setting in global kafka.properties
  flink-cyber/cyber-csd/src/main/descriptor/service.sdl
  flink-cyber/cyber-csd/src/main/scripts/control.sh
  flink-cyber/cyber-jobs/src/main/resources/scripts/cs-start-job
  flink-cyber/cyber-parcel/src/main/meta/permissions.json
Labels: checked on a cluster, ready to review

#13 [CYB-136] Fix issue with parcel installation on the Cluster
  flink-cyber/cyber-csd/src/main/scripts/control.sh
  flink-cyber/cyber-parcel/pom.xml
  flink-cyber/cyber-parcel/src/main/assemblies/meta-assembly.xml
  flink-cyber/cyber-parcel/src/main/assemblies/parcel-assembly.xml
  flink-cyber/cyber-parcel/src/main/meta/permissions.json
Labels: in progress
